bain_capital:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: BAIN_ANALYTICS
      warehouse: COMPUTE_WH
      schema: DEV
      threads: 1
      client_session_keep_alive: True
      connect_retries: 3
      connect_timeout: 300

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: DBT_DEMO
      warehouse: COMPUTE_WH
      schema: PROD
      threads: 8
      client_session_keep_alive: False